name: Run Gradle on Commit
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Checkout Live2D Framework
      run: |
        wget https://cubism.live2d.com/sdk-native/bin/CubismSdkForNative-4-r.1.zip
        unzip CubismSdkForNative-4-r.1.zip
    - name: Copy CubismSdkForNative-4-r.1 Files
      run: |
        cp -R CubismSdkForNative-4-r.1/Core .
        cp -R CubismSdkForNative-4-r.1/Framework .
        cp -R CubismSdkForNative-4-r.1/Samples/OpenGL .
    - name: Build Vly
      run: |
        wget https://raw.githubusercontent.com/nothings/stb/master/stb_image.h
        cp stb_image.h app/src/main/cpp/
        chmod a+x gradlew
        ./gradlew assembleRelease --no-daemon
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - name: Create Release
      uses: actions/create-release@v1
      if: success()
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.slug.outputs.sha8 }}
        release_name: Release ${{ steps.slug.outputs.sha8 }}
        body: |
          Auto Build
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      if: success()
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/app-release.apk
        asset_name: release.apk
        asset_content_type: application/vnd.android.package-archive